CLASS zcl_119jjj_demo_0101 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_119JJJ_DEMO_0101 IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
    out->write('Hello World!').
  ENDMETHOD.
ENDCLASS.
